const $ = (s, el=document) => el.querySelector(s);
const $$ = (s, el=document) => [...el.querySelectorAll(s)];

const demoParams = new URLSearchParams(location.search);
const state = { workspace:demoParams.get('workspace')==='halaja'?'halaja':'kma', view:demoParams.get('view')||(demoParams.get('workspace')==='halaja'?'rabbi-panel':'overview'), screenTitle:'DÍA DE ESTUDIO', screenSubtitle:'En mérito de la familia Cohen', screenMeta:'17 de septiembre · כ״ה אלול', claimed:false };

const nav = {
  kma:[
    {group:'Operación',id:'overview',icon:'◫',label:'Resumen'},
    {id:'clients',icon:'◉',label:'Clientes y donantes'},
    {id:'sales',icon:'↗',label:'Ventas y conceptos'},
    {id:'seller',icon:'◎',label:'Portal del vendedor'},
    {id:'client-portal',icon:'◇',label:'Portal del donador'},
    {group:'Cobranza y tesorería',id:'collections',icon:'✓',label:'Agenda de cobranza'},
    {id:'routes',icon:'⌖',label:'Cobradores y rutas'},
    {id:'cash',icon:'▣',label:'Cajas y custodia'},
    {id:'bank',icon:'≋',label:'Bancos y conciliación'},
    {group:'Módulos especiales',id:'raffles',icon:'#',label:'Rifas'},
    {id:'screens',icon:'▤',label:'Pantallas en vivo'},
    {id:'thanks',icon:'♡',label:'Hakarat Hatov'},
    {id:'expenses',icon:'↙',label:'Egresos y proveedores'},
    {group:'Abrejim',id:'attendance',icon:'◉',label:'Lectores y asistencia'},
    {id:'payroll',icon:'∑',label:'Cálculo de pagos'},
    {group:'Control',id:'reports',icon:'▥',label:'Reportes'},
    {id:'admin',icon:'⚙',label:'Administración'},
    {id:'audit',icon:'◷',label:'Historial y auditoría'}
  ],
  halaja:[
    {group:'Mi turno',id:'rabbi-panel',icon:'人',label:'Mi panel de rabino'},
    {id:'shift-handoff',icon:'⇄',label:'Cambio de turno'},
    {group:'Atención',id:'inbox',icon:'◌',label:'Bandeja compartida'},
    {id:'halaja-team',icon:'◎',label:'Rabinos y disponibilidad'},
    {id:'knowledge',icon:'▤',label:'Respuestas aprobadas'},
    {group:'Control',id:'halaja-analytics',icon:'▥',label:'Métricas'},
    {id:'halaja-settings',icon:'⚙',label:'Configuración'}
  ]
};

const titles={
  overview:'Resumen ejecutivo',clients:'Clientes y donantes',sales:'Ventas y conceptos',seller:'Portal del vendedor','client-portal':'Portal del donador',collections:'Agenda de cobranza',routes:'Cobradores y rutas',cash:'Cajas y cadena de custodia',bank:'Bancos y conciliación',raffles:'Rifas y participaciones',screens:'Estudio de pantallas',thanks:'Hakarat Hatov',expenses:'Egresos y proveedores',attendance:'Lectores y asistencia',payroll:'Cálculo de pagos',reports:'Reportes y análisis',admin:'Administración',audit:'Historial y auditoría','rabbi-panel':'Mi panel de rabino','shift-handoff':'Cambio de turno',inbox:'Bandeja compartida','halaja-team':'Rabinos y disponibilidad',knowledge:'Respuestas aprobadas','halaja-analytics':'Métricas de atención','halaja-settings':'Configuración de Maor Halajá'
};

function pageHead(title,desc,actions=''){
  return `<div class="page-head"><div><h2>${title}</h2><p>${desc}</p></div><div class="actions">${actions}</div></div>`;
}
function metric(icon,value,label,badge='',down=false){return `<div class="metric"><div class="metric-top"><span class="metric-icon">${icon}</span>${badge?`<span class="metric-badge ${down?'down':''}">${badge}</span>`:''}</div><strong>${value}</strong><label>${label}</label></div>`}
function person(initials,name,sub=''){return `<div class="person"><span class="avatar">${initials}</span><span><b>${name}</b><small>${sub}</small></span></div>`}
function status(text,type=''){return `<span class="tag ${type}">${text}</span>`}
function panel(title,body,action='',cls=''){return `<section class="panel ${cls}"><div class="panel-head"><div><h3>${title}</h3></div>${action}</div><div class="panel-body ${cls==='flush'?'flush':''}">${body}</div></section>`}
function bars(values,labels,alt=false){return `<div class="chart">${values.map((v,i)=>`<div class="bar-wrap"><div class="bar ${alt&&i%2?'alt':''}" style="height:${v}%"></div><small>${labels[i]}</small></div>`).join('')}</div>`}

function overview(){return `
  ${pageHead('Buenos días, Eduardo','Así se ve la operación consolidada de KMA hoy.',`<button class="btn" data-action="show-disclaimer">Ver alcance del demo</button><button class="btn primary" data-action="new-sale">+ Nueva venta</button>`)}
  <div class="metric-grid">${metric('$','$1.28 M','Cobrado este mes','+12.4%')}${metric('✓','84%','Cartera al corriente','+4.1%')}${metric('◷','37','Pendientes para hoy','8 urgentes',true)}${metric('◉','96.8%','Lectores sincronizados','3 en línea')}</div>
  <div class="grid-2">
    ${panel('Ingresos y cobranza',`${bars([44,56,52,68,63,79,86],['Lun','Mar','Mié','Jue','Vie','Dom','Hoy'],true)}<div class="chart-legend"><span><i class="dot"></i>Cobrado</span><span><i class="dot blue"></i>Meta acumulada</span></div>`,`<select class="filter"><option>Últimos 7 días</option></select>`)}
    ${panel('Avance por área',`<div class="progress-list">
      <div class="progress-row"><b>Cobranza</b><div class="track"><div class="fill" style="width:84%"></div></div><span>84%</span></div>
      <div class="progress-row"><b>Conciliación</b><div class="track"><div class="fill" style="width:72%"></div></div><span>72%</span></div>
      <div class="progress-row"><b>Rifa 2027</b><div class="track"><div class="fill" style="width:61%"></div></div><span>61%</span></div>
      <div class="progress-row"><b>Asistencia</b><div class="track"><div class="fill" style="width:97%"></div></div><span>97%</span></div>
      <div class="progress-row"><b>Pantallas</b><div class="track"><div class="fill" style="width:100%"></div></div><span>OK</span></div></div>`)}
  </div>
  <div class="grid-2 equal">
    ${panel('Actividad reciente',`<div class="activity">
      <div class="activity-item"><span class="activity-icon">$</span><div><b>Pago conciliado</b><p>Transferencia aplicada a dos cargos.</p></div><time>Hace 4 min</time></div>
      <div class="activity-item"><span class="activity-icon">▤</span><div><b>Pantalla publicada</b><p>Día de estudio · Entrada y Bet Midrash.</p></div><time>12 min</time></div>
      <div class="activity-item"><span class="activity-icon">◉</span><div><b>Lector recuperado</b><p>MB160 Comedor sincronizó 43 eventos.</p></div><time>28 min</time></div>
      <div class="activity-item"><span class="activity-icon">✓</span><div><b>Cobranza reprogramada</b><p>Responsable y próxima fecha asignados.</p></div><time>41 min</time></div></div>`)}
    ${panel('Alertas que requieren atención',`<div class="activity">
      <div class="activity-item"><span class="activity-icon">!</span><div><b>5 depósitos sin identificar</b><p>Total pendiente de aplicación: $38,500.</p></div><span class="tag amber">Revisar</span></div>
      <div class="activity-item"><span class="activity-icon">◷</span><div><b>8 tareas vencen hoy</b><p>Sin confirmación de pago.</p></div><span class="tag red">Urgente</span></div>
      <div class="activity-item"><span class="activity-icon">⌁</span><div><b>2 incidencias de asistencia</b><p>Solicitudes pendientes del supervisor.</p></div><span class="tag blue">Validar</span></div></div>`)}
  </div>`}

function clients(){const rows=[['AM','Abraham M.','Donante recurrente','Secretaría 1','$36,000','Al corriente'],['SR','Sara R.','Rifa 2027','Secretaría 2','$15,000','Pendiente'],['DC','David C.','Día de estudio','Secretaría 1','$8,500','Promesa'],['EM','Esther M.','Mensualidad','Secretaría 3','$4,200','Vencido'],['JA','José A.','Seudá','Secretaría 2','$0','Al corriente']];return `
  ${pageHead('Clientes y donantes','Un expediente único con relaciones, contactos, historial y saldo.',`<button class="btn" data-action="export">Exportar</button><button class="btn primary" data-action="new-client">+ Nuevo cliente</button>`)}
  <div class="stat-strip"><div><b>4,826</b><span>Clientes activos</span></div><div><b>312</b><span>Recurrentes</span></div><div><b>96</b><span>Datos por confirmar</span></div><div><b>11</b><span>Duplicados sugeridos</span></div></div>
  <div class="filters"><input class="filter" placeholder="Buscar nombre, teléfono…"><select class="filter"><option>Todos los tipos</option><option>Donante</option><option>Cliente</option></select><select class="filter"><option>Todas las secretarías</option></select><button class="btn small">Más filtros</button></div>
  ${panel('Directorio',`<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Tipo / campaña</th><th>Responsable</th><th>Saldo</th><th>Estado</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${person(r[0],r[1],'+52 55 •••• '+(1100+Math.floor(Math.random()*8000)))}</td><td>${r[2]}</td><td>${r[3]}</td><td class="money">${r[4]}</td><td>${status(r[5],r[5]==='Al corriente'?'green':r[5]==='Vencido'?'red':'amber')}</td><td><button class="btn small" data-action="open-record">Abrir</button></td></tr>`).join('')}</tbody></table></div>`,'','flush')}`}

function sales(){return `
  ${pageHead('Ventas y conceptos','Cada venta genera cargo, cobranza y contenidos relacionados.',`<button class="btn">Carga masiva</button><button class="btn primary" data-action="new-sale">+ Registrar venta</button>`)}
  <div class="metric-grid">${metric('↗','$486,300','Ventas del mes','+8.7%')}${metric('◫','128','Operaciones','17 recurrentes')}${metric('%','$34,920','Comisión proyectada')}${metric('▤','31','Piezas para pantallas','100% generadas')}</div>
  <div class="grid-2">
    ${panel('Venta → operación',`<div class="cash-flow"><div class="cash-node"><div class="big-icon">1</div><b>Venta</b><small>Cliente + concepto</small></div><span class="flow-arrow">›</span><div class="cash-node"><div class="big-icon">2</div><b>Cargo</b><small>CxC + folio</small></div><span class="flow-arrow">›</span><div class="cash-node"><div class="big-icon">3</div><b>Cobranza</b><small>Responsable + fecha</small></div><span class="flow-arrow">›</span><div class="cash-node"><div class="big-icon">4</div><b>Pantalla</b><small>Si corresponde</small></div></div>`)}
    ${panel('Conceptos más vendidos',`<div class="progress-list"><div class="progress-row"><b>Día de estudio</b><div class="track"><div class="fill" style="width:88%"></div></div><span>42</span></div><div class="progress-row"><b>Mensualidad</b><div class="track"><div class="fill" style="width:72%"></div></div><span>35</span></div><div class="progress-row"><b>Rifa 2027</b><div class="track"><div class="fill" style="width:60%"></div></div><span>29</span></div><div class="progress-row"><b>Seudá</b><div class="track"><div class="fill" style="width:40%"></div></div><span>19</span></div></div>`)}
  </div>
  ${panel('Ventas recientes',`<div class="table-wrap"><table><thead><tr><th>Folio</th><th>Cliente</th><th>Concepto</th><th>Vendedor</th><th>Importe</th><th>Cobrado</th><th>Estado</th></tr></thead><tbody>
    <tr><td>V-10482</td><td>${person('AM','Abraham M.')}</td><td>Día de estudio</td><td>R. David</td><td class="money">$12,000</td><td>$12,000</td><td>${status('Pagada','green')}</td></tr>
    <tr><td>V-10481</td><td>${person('SR','Sara R.')}</td><td>Rifa 2027</td><td>R. Rafael</td><td class="money">$15,000</td><td>$5,000</td><td>${status('Parcial','amber')}</td></tr>
    <tr><td>V-10480</td><td>${person('DC','David C.')}</td><td>Mensualidad</td><td>R. Juni</td><td class="money">$4,500</td><td>$0</td><td>${status('Por cobrar','blue')}</td></tr></tbody></table></div>`,'','flush')}`}

function seller(){return `${pageHead('Mi portal de vendedor','Resultados, cartera y próximos pasos personales.',`<button class="btn primary" data-action="new-sale">+ Nueva venta</button>`)}
  <div class="metric-grid">${metric('$','$182,400','Vendido este mes','+14%')}${metric('✓','$121,800','Efectivamente cobrado')}${metric('%','$8,526','Comisión acumulada')}${metric('◎','76%','Avance a mi meta')}</div>
  <div class="grid-2">${panel('Mi avance',`${bars([35,48,42,60,67,74,82],['Mar','Abr','May','Jun','Jul','Ago','Sep'],true)}<div class="chart-legend"><span><i class="dot"></i>Yo</span><span><i class="dot blue"></i>Meta</span></div>`)}${panel('Sugerencias para hoy',`<div class="activity"><div class="activity-item"><span class="activity-icon">1</span><div><b>Retomar 6 promesas</b><p>Vencen en los próximos tres días.</p></div><button class="btn small">Ver</button></div><div class="activity-item"><span class="activity-icon">2</span><div><b>Rifa: compradores anteriores</b><p>18 contactos sin venta este año.</p></div><button class="btn small">Ver</button></div><div class="activity-item"><span class="activity-icon">3</span><div><b>Datos incompletos</b><p>Confirma teléfono de 4 clientes.</p></div><button class="btn small">Ver</button></div></div>`)} </div>
  ${panel('Mi cartera',`<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Último contacto</th><th>Saldo</th><th>Próxima acción</th><th></th></tr></thead><tbody><tr><td>${person('SR','Sara R.')}</td><td>Ayer</td><td class="money">$10,000</td><td>Jue 18 · WhatsApp</td><td><button class="btn small">Contactar</button></td></tr><tr><td>${person('EM','Esther M.')}</td><td>Hace 8 días</td><td class="money">$4,200</td><td>Hoy · Llamada</td><td><button class="btn small">Contactar</button></td></tr><tr><td>${person('JA','José A.')}</td><td>Hace 2 días</td><td class="money">$7,500</td><td>Vie 19 · Visita</td><td><button class="btn small">Ver</button></td></tr></tbody></table></div>`,'','flush')}`}

function clientPortal(){return `${pageHead('Portal del donador','Vista privada para consultar saldo, donar y conocer opciones del kolel.',`<button class="btn" data-action="impersonate">Vista como donador</button>`)}
  <div class="grid-2"><div><div class="panel"><div class="panel-body"><span class="tag green">Cuenta al corriente</span><h2 style="color:var(--ink);margin:15px 0 4px">Hola, Abraham</h2><p style="font-size:10px">Gracias por ser parte de KMA.</p><div class="stat-strip" style="margin-top:20px;margin-bottom:0"><div><b>$0</b><span>Saldo vencido</span></div><div><b>$12,000</b><span>Donado este mes</span></div><div><b>7</b><span>Recibos 2026</span></div><div><b>1</b><span>Próximo cargo</span></div></div></div></div>${panel('Movimientos recientes',`<table><tbody><tr><td>17 Sep</td><td>Día de estudio</td><td class="money">$12,000</td><td>${status('Pagado','green')}</td></tr><tr><td>01 Sep</td><td>Mensualidad</td><td class="money">$4,500</td><td>${status('Pagado','green')}</td></tr><tr><td>15 Ago</td><td>Rifa 2027</td><td class="money">$15,000</td><td>${status('Recibo','blue')}</td></tr></tbody></table>`,'','flush')}</div><div>${panel('Donar ahora',`<div class="progress-list"><button class="btn primary" data-action="payment">Hacer un donativo</button><button class="btn">Día de estudio</button><button class="btn">Patrocinar una seudá</button><button class="btn">Apoyar a un abrej</button></div><p class="small" style="margin-top:10px">Opciones, importes y disponibilidad configurables desde administración.</p>`)}${panel('Mi cuenta',`<div class="progress-list"><button class="btn">Descargar estado de cuenta</button><button class="btn">Consultar recibos</button><button class="btn">Actualizar mis datos</button></div>`)}</div></div>`}

function collections(){return `${pageHead('Agenda de cobranza','Todo pendiente conserva responsable, fecha y siguiente acción.',`<button class="btn">Asignar en bloque</button><button class="btn primary" data-action="new-task">+ Nueva tarea</button>`)}
  <div class="stat-strip"><div><b>37</b><span>Para hoy</span></div><div><b>8</b><span>Urgentes</span></div><div><b>12</b><span>Promesas</span></div><div><b>$186,900</b><span>Saldo gestionado</span></div></div>
  <div class="kanban"><div class="kanban-col"><div class="kanban-title">Nuevos <span>9</span></div>${task('Abraham M.','$12,000 · Día de estudio','Hoy 10:30','WhatsApp')}${task('Sara R.','$10,000 · Rifa','Hoy 11:15','Llamada')}</div><div class="kanban-col"><div class="kanban-title">En contacto <span>11</span></div>${task('Esther M.','$4,200 · Mensualidad','Esperando respuesta','Secretaría 3')}${task('David C.','$8,500 · Seudá','Mensaje enviado','Secretaría 1')}</div><div class="kanban-col"><div class="kanban-title">Promesa de pago <span>12</span></div>${task('José A.','$7,500 · Colecta','Mañana','Transferencia')}${task('Miriam S.','$15,000 · Rifa','Viernes','Cobrador')}</div><div class="kanban-col"><div class="kanban-title">Requiere visita <span>5</span></div>${task('Cliente 042','$21,000 · Varios','Ruta Norte','Cobrador 2')}${task('Cliente 088','$9,800 · Mensualidad','Ruta Centro','Cobrador 1')}</div></div>`}
function task(name,amount,when,tagText){return `<div class="task"><b>${name}</b><p>${amount}</p><div class="task-foot"><span class="tag blue">${tagText}</span><small>${when}</small></div></div>`}

function routes(){return `${pageHead('Cobradores y rutas','Visitas, evidencias, cobros parciales y entrega de efectivo.',`<button class="btn">Optimizar ruta</button><button class="btn primary" data-action="new-route">+ Crear ruta</button>`)}<div class="grid-2"><div>${panel('Ruta Centro · Cobrador 1',`<div class="route-map"><div class="road r1"></div><div class="road r2"></div><div class="road r3"></div><i class="map-pin" style="left:20%;top:25%"></i><span class="pin-label" style="left:12%;top:39%">1 · $8,500</span><i class="map-pin" style="left:52%;top:45%;background:#ca38d6"></i><span class="pin-label" style="left:45%;top:60%">2 · $4,200</span><i class="map-pin" style="left:75%;top:20%;background:#138a65"></i><span class="pin-label" style="left:67%;top:34%">3 · Cobrado</span></div>`)} </div><div>${panel('Resumen de la ruta',`<div class="metric-grid" style="grid-template-columns:1fr 1fr">${metric('⌖','8','Visitas')}${metric('$','$74,300','Por cobrar')}${metric('✓','3','Completadas')}${metric('◷','4h 10m','Estimado')}</div><div class="activity"><div class="activity-item"><span class="activity-icon">1</span><div><b>Cliente 042</b><p>Importe fijo · requiere firma.</p></div><span class="tag blue">Siguiente</span></div><div class="activity-item"><span class="activity-icon">2</span><div><b>Cliente 088</b><p>Parcial sólo con autorización.</p></div><span class="tag">12:20</span></div></div>`)}${panel('Última entrega',`<p style="font-size:9px">Cobrador 2 → Caja Dirección</p><b class="money" style="font-size:20px">$38,500</b><p class="small">Aceptada hoy 09:42 · evidencia completa.</p>`)}</div></div>`}

function cash(){return `${pageHead('Cajas y cadena de custodia','El efectivo conserva dueño, aceptación y saldo en cada paso.',`<button class="btn">Arqueo</button><button class="btn primary" data-action="cash-transfer">+ Transferir custodia</button>`)}
  ${panel('Flujo de efectivo',`<div class="cash-flow"><div class="cash-node"><div class="big-icon">C</div><b>Cobrador 1</b><small>$18,500</small></div><span class="flow-arrow">›</span><div class="cash-node"><div class="big-icon">S</div><b>Secretaría</b><small>$42,300</small></div><span class="flow-arrow">›</span><div class="cash-node"><div class="big-icon">D</div><b>Dirección</b><small>$86,900</small></div><span class="flow-arrow">›</span><div class="cash-node"><div class="big-icon">B</div><b>Banco</b><small>Depósito pendiente</small></div></div>`)}
  <div class="grid-3"><div class="metric"><span class="metric-icon">$</span><strong>$147,700</strong><label>Efectivo bajo custodia</label></div><div class="metric"><span class="metric-icon">✓</span><strong>12</strong><label>Entregas aceptadas hoy</label></div><div class="metric"><span class="metric-icon">!</span><strong>1</strong><label>Diferencia por revisar</label></div></div>
  ${panel('Movimientos recientes',`<table><thead><tr><th>Hora</th><th>Origen</th><th>Destino</th><th>Monto</th><th>Estatus</th><th>Evidencia</th></tr></thead><tbody><tr><td>09:42</td><td>Cobrador 2</td><td>Dirección</td><td class="money">$38,500</td><td>${status('Aceptado','green')}</td><td>Firma + foto</td></tr><tr><td>09:18</td><td>Secretaría</td><td>Dirección</td><td class="money">$22,000</td><td>${status('Aceptado','green')}</td><td>Firma</td></tr><tr><td>08:55</td><td>Cobrador 1</td><td>Secretaría</td><td class="money">$14,800</td><td>${status('Diferencia','red')}</td><td>Revisar $200</td></tr></tbody></table>`,'','flush')}`}

function bank(){return `${pageHead('Bancos y conciliación','Importa, sugiere coincidencias y deja lo incierto para revisión.',`<button class="btn">Importar archivo</button><button class="btn primary" data-action="auto-match">Sugerir coincidencias</button>`)}
  <div class="metric-grid">${metric('$','$727,350','Depósitos importados','23 movimientos')}${metric('✓','18','Conciliados','78%')}${metric('?','5','Sin identificar','Revisar',true)}${metric('≋','$38,500','Pendiente de aplicar')}</div>
  ${panel('Bandeja de conciliación',`<div class="bank-row" style="font-weight:800;color:#999"><span>Fecha</span><span>Descripción bancaria</span><span>Monto</span><span>Sugerencia</span><span>Acción</span></div>
    ${bankRow('17 Sep','SPEI recibido · Donativo septiembre','$12,000','Abraham M.','96')}${bankRow('17 Sep','Pago cuenta de tercero · Rifa','$15,000','Sara R. · 2 cargos','88')}${bankRow('16 Sep','Depósito cheque · Referencia parcial','$18,000','David C.','72')}${bankRow('16 Sep','Traspaso entre cuentas','$300,000','Movimiento interno','99')}${bankRow('15 Sep','Validación de cuenta','$0.01','No operativo','100')}`,'','flush')}
  <div class="grid-2 equal">${panel('Reglas aprendidas',`<div><span class="tag">Referencia</span> <span class="tag">Cuenta origen</span> <span class="tag">Monto</span> <span class="tag">Fecha</span> <span class="tag">Nombre fiscal</span></div><p class="small" style="margin-top:12px">Las reglas sugieren; las coincidencias ambiguas no se aplican solas.</p>`)}${panel('Casos del archivo recibido',`<div><span class="tag blue">SPEI</span> <span class="tag blue">Tercero</span> <span class="tag blue">Cheque</span> <span class="tag blue">Traspaso</span> <span class="tag blue">Varias facturas</span></div><p class="small" style="margin-top:12px">El depositante, cliente y receptor fiscal pueden ser distintos.</p>`)}</div>`}
function bankRow(date,desc,amount,suggestion,conf){return `<div class="bank-row"><span>${date}</span><span><b style="color:var(--ink)">${desc}</b></span><span class="money">${amount}</span><span>${suggestion}<div class="confidence"><i style="width:${conf}%"></i></div><small>${conf}% confianza</small></span><span><button class="btn small" data-action="reconcile">Aplicar</button></span></div>`}

function raffles(){return `${pageHead('Rifa 2027','Boletos, compradores, participaciones y venta sin duplicados.',`<button class="btn">Reporte histórico</button><button class="btn primary" data-action="sell-ticket">+ Vender boleto</button>`)}<div class="metric-grid">${metric('#','1,000','Boletos totales')}${metric('✓','612','Vendidos','61.2%')}${metric('◫','48','Con participación')}${metric('$','$8.7 M','Venta comprometida')}</div><div class="grid-2"><div>${panel('Mapa de boletos',`<div class="ticket-grid">${Array.from({length:25},(_,i)=>`<div class="ticket ${i<15?'sold':i<19?'partial':''}" data-action="ticket"><b>#${String(i+401).padStart(4,'0')}</b><span>${i<15?'Vendido':i<19?'Parcial':'Disponible'}</span></div>`).join('')}</div>`)}</div><div>${panel('Venta destacada',`<span class="tag amber">Participación compartida</span><h3 style="font-size:18px;margin:13px 0;color:var(--ink)">Boleto #0418</h3><div class="progress-list"><div class="progress-row"><b>Familia A.</b><div class="track"><div class="fill" style="width:50%"></div></div><span>50%</span></div><div class="progress-row"><b>Familia C.</b><div class="track"><div class="fill" style="width:30%"></div></div><span>30%</span></div><div class="progress-row"><b>Disponible</b><div class="track"><div class="fill" style="width:20%;background:#ddd"></div></div><span>20%</span></div></div>`)}${panel('Oportunidades',`<div class="activity"><div class="activity-item"><span class="activity-icon">↗</span><div><b>Compradores 2026 sin compra</b><p>134 contactos disponibles.</p></div><button class="btn small">Ver</button></div><div class="activity-item"><span class="activity-icon">★</span><div><b>Compradores de 5 años</b><p>42 clientes frecuentes.</p></div><button class="btn small">Ver</button></div></div>`)}</div></div>`}

function screens(){return `${pageHead('Estudio de pantallas','Crea desde una venta o anuncio; publica en vivo a uno o varios destinos.',`<button class="btn" data-action="preview-screen">Vista previa</button><button class="btn primary" data-action="quick-announcement">+ Anuncio rápido</button>`)}
  <div class="screen-studio"><aside class="slide-list"><b style="font-size:9px;color:var(--ink)">Plantillas</b><div class="slide-thumb active"><b>Día de estudio</b><br><small>Dinámica</small></div><div class="slide-thumb"><b>Minjá hoy</b><br><small>Anuncio rápido</small></div><div class="slide-thumb"><b>Seudá</b><br><small>Dinámica</small></div><div class="slide-thumb"><b>Aviso general</b><br><small>Diseño libre</small></div><button class="btn small" style="width:100%">+ Nueva plantilla</button></aside>
    <div class="canvas-wrap"><div class="canvas" id="screenCanvas"><h4 id="canvasTitle">${state.screenTitle}</h4><p id="canvasSubtitle">${state.screenSubtitle}</p><small id="canvasMeta" style="margin-top:9px;z-index:1;opacity:.78">${state.screenMeta}</small></div></div>
    <aside class="properties"><b style="font-size:9px;color:var(--ink)">Propiedades</b><label>Título</label><input id="screenTitleInput" value="${state.screenTitle}"><label>Mensaje</label><textarea id="screenSubtitleInput">${state.screenSubtitle}</textarea><label>Transición</label><select><option>Desvanecer</option><option>Deslizar</option><option>Zoom suave</option></select><label>Tiempo visible</label><select><option>12 segundos</option><option>20 segundos</option><option>1 minuto</option></select><label>Pantallas</label><select><option>Entrada + Bet Midrash</option><option>Todas</option><option>Comedor</option></select><button class="btn primary" style="width:100%;margin-top:12px" data-action="publish-screen">Publicar ahora</button></aside></div>
  <div class="grid-3" style="margin-top:15px"><div class="device"><div class="device-head"><span class="device-icon">▤</span>${status('En línea','green')}</div><h3>Entrada</h3><p>Días de estudio · avisos generales</p></div><div class="device"><div class="device-head"><span class="device-icon">▤</span>${status('En línea','green')}</div><h3>Bet Midrash</h3><p>Dedicatorias · horarios</p></div><div class="device"><div class="device-head"><span class="device-icon">▤</span>${status('Sincronizando','amber')}</div><h3>Comedor</h3><p>Seudot · agradecimientos</p></div></div>`}

function thanks(){return `${pageHead('Hakarat Hatov','Seguimiento de agradecimientos, obsequios y relaciones con donadores.',`<button class="btn">Configurar reglas</button><button class="btn primary" data-action="new-thanks">+ Registrar agradecimiento</button>`)}<div class="metric-grid">${metric('♡','28','Pendientes sugeridos')}${metric('✓','46','Completados este mes','+9')}${metric('◷','12','Sin contacto >90 días','Revisar',true)}${metric('★','7','Obsequios por entregar')}</div><div class="grid-2">${panel('Agenda de agradecimientos',`<div class="activity"><div class="activity-item"><span class="activity-icon">♡</span><div><b>Donativo significativo</b><p>Llamada personal sugerida · Dirección.</p></div><span class="tag red">Hoy</span></div><div class="activity-item"><span class="activity-icon">✉</span><div><b>Campaña completada</b><p>Carta de agradecimiento preparada.</p></div><span class="tag amber">Revisar</span></div><div class="activity-item"><span class="activity-icon">★</span><div><b>Donante recurrente</b><p>Obsequio anual pendiente de entrega.</p></div><span class="tag blue">Viernes</span></div></div>`)}${panel('Reglas activas',`<div class="progress-list"><div class="task"><b>Donativo mayor a $50,000</b><p>Llamada de Dirección dentro de 48 h.</p>${status('Activa','green')}</div><div class="task"><b>12 meses consecutivos</b><p>Obsequio y carta personalizada.</p>${status('Activa','green')}</div><div class="task"><b>Sin contacto 90 días</b><p>Crear tarea para responsable de relación.</p>${status('Activa','green')}</div></div>`)}</div>`}

function expenses(){return `${pageHead('Egresos y proveedores','Compras, cuentas por pagar, costos y movimientos no operativos.',`<button class="btn">Importar comprobantes</button><button class="btn primary" data-action="new-expense">+ Registrar egreso</button>`)}<div class="metric-grid">${metric('↙','$284,900','Egresos del mes','-6.2%')}${metric('◷','$91,300','Cuentas por pagar')}${metric('✓','24','Pagos completados')}${metric('!','3','Comprobantes faltantes','Revisar',true)}</div>${panel('Cuentas por pagar',`<table><thead><tr><th>Proveedor</th><th>Concepto</th><th>Vence</th><th>Monto</th><th>Clasificación</th><th>Estado</th></tr></thead><tbody><tr><td>${person('PL','Proveedor limpieza')}</td><td>Mantenimiento</td><td>18 Sep</td><td class="money">$18,600</td><td>Operativo</td><td>${status('Por aprobar','amber')}</td></tr><tr><td>${person('PS','Proveedor seguros')}</td><td>Seguro médico</td><td>20 Sep</td><td class="money">$42,000</td><td>Operativo</td><td>${status('Programado','blue')}</td></tr><tr><td>${person('TF','Tercero fiduciario')}</td><td>Movimiento de paso</td><td>Hoy</td><td class="money">$30,700</td><td>No operativo</td><td>${status('Conciliado','green')}</td></tr></tbody></table>`,'','flush')}<div class="grid-2 equal">${panel('Resultado vs flujo',`${bars([52,70,43,64,75,48],['Abr','May','Jun','Jul','Ago','Sep'],true)}<div class="chart-legend"><span><i class="dot"></i>Egresos</span><span><i class="dot blue"></i>Costos recuperables</span></div>`)}${panel('Controles',`<div class="progress-list"><div class="progress-row"><b>Con comprobante</b><div class="track"><div class="fill" style="width:94%"></div></div><span>94%</span></div><div class="progress-row"><b>Aprobados</b><div class="track"><div class="fill" style="width:88%"></div></div><span>88%</span></div><div class="progress-row"><b>En presupuesto</b><div class="track"><div class="fill" style="width:91%"></div></div><span>91%</span></div></div>`)}</div>`}

function attendance(){return `${pageHead('Lectores y asistencia','Módulo propio conectado directamente a tres ZKTeco MB160.',`<button class="btn">Ver marcaciones</button><button class="btn primary" data-action="sync-readers">Sincronizar lectores</button>`)}<div class="device-grid">${device('Entrada','192.168.1.31','Hoy 11:04','1,482','green')}${device('Bet Midrash','192.168.1.32','Hoy 11:03','1,396','green')}${device('Comedor','192.168.1.33','Hoy 10:58','1,228','amber')}</div><div class="grid-2" style="margin-top:15px">${panel('Asistencia de hoy',`${bars([88,93,96,91,97,84],['Shajrit','Seder A','Halajot','Seder B','Kolel E.','Musar'],true)}<div class="chart-legend"><span><i class="dot"></i>Presente</span><span><i class="dot blue"></i>A tiempo</span></div>`)}${panel('Incidencias',`<div class="activity"><div class="activity-item"><span class="activity-icon">?</span><div><b>Sin salida registrada</b><p>2 abrejim · Seder A.</p></div><button class="btn small">Revisar</button></div><div class="activity-item"><span class="activity-icon">◷</span><div><b>Retardo reportado</b><p>Comparar declaración vs lector.</p></div><button class="btn small">Validar</button></div><div class="activity-item"><span class="activity-icon">⌁</span><div><b>43 eventos recuperados</b><p>Comedor volvió a la red.</p></div>${status('Resuelto','green')}</div></div>`)}</div><div class="callout"></div>`}
function device(name,ip,last,events,type){return `<div class="device"><div class="device-head"><span class="device-icon">◉</span>${status(type==='green'?'En línea':'Revisar red',type)}</div><h3>MB160 · ${name}</h3><p>Conexión directa KMA</p><dl><div><dt>IP</dt><dd>${ip}</dd></div><div><dt>Último contacto</dt><dd>${last}</dd></div><div><dt>Eventos hoy</dt><dd>${events}</dd></div><div><dt>Cola pendiente</dt><dd>${type==='green'?'0':'6'}</dd></div></dl><button class="btn small" data-action="device-detail">Abrir dispositivo</button></div>`}

function payroll(){return `${pageHead('Cálculo de pagos','Reglas versionadas, explicación por componente y comparación contra asistencia.',`<button class="btn">Cargar incidencias</button><button class="btn primary" data-action="calculate-payroll">Calcular quincena</button>`)}<div class="payroll-flow"><div class="calc-card"><small>Parámetro</small><strong>$15k</strong><b>Base quincenal</b><p>Editable por periodo.</p></div><div class="calc-card"><small>Distribución</small><strong>55%</strong><b>Seder A</b><p>Tefilá + seder principal.</p></div><div class="calc-card"><small>Distribución</small><strong>45%</strong><b>Seder B</b><p>Seder + Kolel Ereb.</p></div><div class="calc-card"><small>Factor</small><strong>97.5%</strong><b>Ajuste final</b><p>Cuando corresponde.</p></div></div><div class="grid-2" style="margin-top:15px">${panel('Componentes del cálculo',`<div class="progress-list"><div class="progress-row"><b>Base + hijos</b><div class="track"><div class="fill" style="width:100%"></div></div><span>$</span></div><div class="progress-row"><b>Tefilá/retardos</b><div class="track"><div class="fill" style="width:22%;background:#eaa743"></div></div><span>−</span></div><div class="progress-row"><b>Sedarim</b><div class="track"><div class="fill" style="width:14%;background:#eaa743"></div></div><span>−</span></div><div class="progress-row"><b>Exámenes</b><div class="track"><div class="fill" style="width:8%;background:#3768f7"></div></div><span>±</span></div><div class="progress-row"><b>Extras manuales</b><div class="track"><div class="fill" style="width:12%;background:#138a65"></div></div><span>+</span></div></div>`)}${panel('Estado del periodo',`<div class="activity"><div class="activity-item"><span class="activity-icon">✓</span><div><b>Marcaciones recibidas</b><p>3 lectores · 100% sincronizado.</p></div>${status('Completo','green')}</div><div class="activity-item"><span class="activity-icon">◷</span><div><b>Incidencias</b><p>4 pendientes de aprobación.</p></div>${status('Pendiente','amber')}</div><div class="activity-item"><span class="activity-icon">∑</span><div><b>Cálculo preliminar</b><p>Listo para ejecutar.</p></div>${status('Listo','blue')}</div></div>`)}</div>${panel('Vista previa de pagos',`<table><thead><tr><th>Abrej</th><th>Base</th><th>Hijos</th><th>Asistencia</th><th>Otros</th><th>Total</th><th>Estado</th></tr></thead><tbody><tr><td>${person('A1','Abrej 001')}</td><td>$15,000</td><td>$9,000</td><td>−$450</td><td>+$600</td><td class="money">$23,571</td><td>${status('Validado','green')}</td></tr><tr><td>${person('A2','Abrej 002')}</td><td>$15,000</td><td>$6,000</td><td>−$1,275</td><td>$0</td><td class="money">$19,232</td><td>${status('Revisar','amber')}</td></tr><tr><td>${person('A3','Abrej 003')}</td><td>$15,000</td><td>$12,000</td><td>$0</td><td>+$1,000</td><td class="money">$27,300</td><td>${status('Validado','green')}</td></tr></tbody></table>`,'','flush')}`}

function reports(){return `${pageHead('Reportes y análisis','Información operativa configurable y exportable.',`<button class="btn primary" data-action="new-report">+ Crear vista</button>`)}<div class="report-grid">${report('↗','Ventas y cobrado','Por concepto, vendedor y periodo')}${report('✓','Cartera y cobranza','Vencimiento, responsable y promesas')}${report('≋','Bancos','Conciliados y no identificados')}${report('▣','Cajas','Custodia, arqueos y diferencias')}${report('#','Rifas','Boletos, participaciones y comparativos')}${report('◉','Asistencia','Sedarim, retardos e incidencias')}${report('∑','Pagos a abrejim','Componentes y variaciones')}${report('↙','Egresos','Proveedor, concepto y presupuesto')}${report('♡','Hakarat Hatov','Pendientes y frecuencia')}</div><div class="grid-2" style="margin-top:15px">${panel('Indicadores consolidados',`${bars([35,50,45,68,72,80,86],['Mar','Abr','May','Jun','Jul','Ago','Sep'],true)}`)}${panel('Vistas guardadas',`<div class="activity"><div class="activity-item"><span class="activity-icon">1</span><div><b>Cierre semanal Dirección</b><p>12 indicadores · actualizado hoy.</p></div><button class="btn small">Abrir</button></div><div class="activity-item"><span class="activity-icon">2</span><div><b>Cobranza por secretaría</b><p>Filtros y columnas personalizados.</p></div><button class="btn small">Abrir</button></div><div class="activity-item"><span class="activity-icon">3</span><div><b>Comparativo rifas</b><p>Últimos cinco ciclos.</p></div><button class="btn small">Abrir</button></div></div>`)}</div>`}
function report(icon,title,sub){return `<div class="report"><span class="report-icon">${icon}</span><div><b>${title}</b><small>${sub}</small></div><button class="btn small" style="margin-left:auto">Abrir</button></div>`}

function admin(){return `${pageHead('Administración','Todos los criterios generales editables desde el panel.',`<button class="btn primary" data-action="save-settings">Guardar cambios</button>`)}<div class="settings-layout"><div class="settings-tabs"><button class="active">Empresa</button><button>Usuarios y roles</button><button>Conceptos</button><button>Cobranza</button><button>Bancos</button><button>Pantallas</button><button>Asistencia</button><button>Pagos</button><button>Notificaciones</button><button>Seguridad</button></div><div>${panel('Configuración general',`<div class="form-grid"><div class="field"><label>Nombre de la empresa final</label><input value="Kolel Maor Abraham"></div><div class="field"><label>Moneda principal</label><select><option>MXN — Peso mexicano</option></select></div><div class="field"><label>Zona horaria</label><select><option>America/Mexico_City</option></select></div><div class="field"><label>Formato de fecha</label><select><option>DD/MM/AAAA</option></select></div><div class="field"><label>Idioma principal</label><select><option>Español</option><option>Hebreo</option></select></div><div class="field"><label>Calendario</label><select><option>Civil + hebreo</option></select></div></div>`)}${panel('Automatizaciones',`<div class="activity"><div class="activity-item"><span class="activity-icon">✓</span><div><b>Crear tarea al registrar venta</b><p>Responsable y fecha según concepto.</p></div><input type="checkbox" checked></div><div class="activity-item"><span class="activity-icon">▤</span><div><b>Generar pantalla desde venta</b><p>Según mapeo concepto–plantilla–destino.</p></div><input type="checkbox" checked></div><div class="activity-item"><span class="activity-icon">≋</span><div><b>Sugerir conciliación bancaria</b><p>Nunca aplicar casos ambiguos automáticamente.</p></div><input type="checkbox" checked></div></div>`)}</div></div>`}

function audit(){return `${pageHead('Historial y auditoría','Cambios sensibles, aprobaciones y antes/después.',`<button class="btn">Exportar historial</button>`)}<div class="filters"><input class="filter" placeholder="Buscar usuario, registro…"><select class="filter"><option>Todos los módulos</option></select><select class="filter"><option>Todas las acciones</option></select></div>${panel('Eventos recientes',`<table><thead><tr><th>Fecha/hora</th><th>Usuario</th><th>Módulo</th><th>Acción</th><th>Registro</th><th>Resultado</th></tr></thead><tbody><tr><td>17 Sep · 11:06</td><td>${person('DR','Dirección')}</td><td>Bancos</td><td>Aplicó coincidencia</td><td>Movimiento #B-4821</td><td>${status('Correcto','green')}</td></tr><tr><td>17 Sep · 10:58</td><td>${person('SO','Secretaría 1')}</td><td>Clientes</td><td>Solicitó cambio de nombre</td><td>Cliente #1842</td><td>${status('Por aprobar','amber')}</td></tr><tr><td>17 Sep · 10:44</td><td>${person('OP','Operación')}</td><td>Pantallas</td><td>Publicó anuncio</td><td>Minjá 1:45 pm</td><td>${status('Publicado','green')}</td></tr><tr><td>17 Sep · 10:22</td><td>${person('AS','Asistencia')}</td><td>Lectores</td><td>Reprocesó eventos</td><td>MB160 Comedor</td><td>${status('43 recibidos','blue')}</td></tr><tr><td>17 Sep · 09:42</td><td>${person('CJ','Caja')}</td><td>Custodia</td><td>Aceptó entrega</td><td>$38,500</td><td>${status('Firmado','green')}</td></tr></tbody></table>`,'','flush')}`}

function rabbiPanel(){return `${pageHead('Shalom, R. Juni','Tu turno está activo desde las 08:00. Aquí puedes trabajar tus casos o consultar la bandeja completa.',`<button class="btn" data-action="switch-shift">Cambiar turno antes</button><button class="btn danger" data-action="end-shift">Acabar turno</button>`)}
  <div class="callout" style="margin-bottom:16px"><div>${person('RJ','R. Juni','Turno actual · 08:00–14:00')}</div><div style="display:flex;align-items:center;gap:8px">${status('Disponible','green')}<span class="small">Siguiente: R. Naftaly · 14:00</span></div></div>
  <div class="metric-grid">${metric('◌','4','Mis casos abiertos','1 urgente',true)}${metric('✓','11','Respondidos hoy')}${metric('◷','12 min','Mi primera atención','−4 min')}${metric('◎','2 h 18','Restante del turno')}</div>
  <div class="filters"><button class="btn primary" data-action="rabbi-filter" data-filter="mine">Mis casos</button><button class="btn" data-action="rabbi-filter" data-filter="all">Todos los casos</button><select class="filter"><option>Todos los temas</option><option>Shabat</option><option>Kashrut</option><option>Tefilá</option></select><select class="filter"><option>Abiertos y pendientes</option><option>Sin asignar</option><option>Resueltos</option></select></div>
  <div class="grid-2 equal">
    ${panel('Mis casos activos',`<div class="activity"><div class="activity-item"><span class="activity-icon">!</span><div><b>David M. · Shabat</b><p>Esperando respuesta · SLA 13 min.</p></div>${status('Urgente','red')}</div><div class="activity-item"><span class="activity-icon">◷</span><div><b>Sara R. · Kashrut</b><p>Audio transcrito · hace 8 min.</p></div><button class="btn small" data-action="open-rabbi-case">Abrir</button></div><div class="activity-item"><span class="activity-icon">↩</span><div><b>Comunidad Norte · Tefilá</b><p>Requiere seguimiento del grupo.</p></div><button class="btn small" data-action="open-rabbi-case">Abrir</button></div><div class="activity-item"><span class="activity-icon">✓</span><div><b>José A. · Berajot</b><p>Respuesta enviada; falta cerrar.</p></div><button class="btn small" data-action="open-rabbi-case">Abrir</button></div></div>`)}
    ${panel('Vista general del equipo',`<div class="activity"><div class="activity-item"><span class="avatar">RJ</span><div><b>R. Juni · Tú</b><p>4 casos · disponible.</p></div>${status('En turno','green')}</div><div class="activity-item"><span class="avatar">RN</span><div><b>R. Naftaly</b><p>2 casos · entra a las 14:00.</p></div>${status('Próximo','blue')}</div><div class="activity-item"><span class="avatar">RO</span><div><b>R. Ovadia</b><p>3 casos · respaldo.</p></div>${status('Disponible','green')}</div></div><div class="notice" style="margin-top:12px"><b>Permisos de este perfil</b><p>Puedes ver todos los mensajes, pero “Mis casos” muestra primero los que tomaste o te asignaron.</p></div>`)}
  </div>`}

function shiftHandoff(){return `${pageHead('Cambio de turno','Entrega ordenada de casos, contexto y responsabilidades entre jajamim.',`<button class="btn primary" data-action="switch-shift">Iniciar cambio anticipado</button>`)}
  <div class="grid-3"><div class="device"><div class="device-head"><span class="avatar">RJ</span>${status('En turno','green')}</div><h3>R. Juni</h3><p>08:00–14:00</p><dl><div><dt>Casos abiertos</dt><dd>4</dd></div><div><dt>Sin entregar</dt><dd>2</dd></div></dl></div><div class="device" style="border-color:#d9ceff;background:#faf8ff"><div class="device-head"><span class="avatar">⇄</span>${status('Preparando','amber')}</div><h3>Entrega de guardia</h3><p>Contexto, casos y notas internas.</p><dl><div><dt>Programada</dt><dd>13:55</dd></div><div><dt>Confirmación</dt><dd>Ambos</dd></div></dl></div><div class="device"><div class="device-head"><span class="avatar">RN</span>${status('Siguiente','blue')}</div><h3>R. Naftaly</h3><p>14:00–20:00</p><dl><div><dt>Casos a recibir</dt><dd>2</dd></div><div><dt>Disponible</dt><dd>Sí</dd></div></dl></div></div>
  <div class="grid-2" style="margin-top:16px">${panel('Casos que requieren entrega',`<table><thead><tr><th>Caso</th><th>Tema</th><th>Estado</th><th>Entrega</th></tr></thead><tbody><tr><td>David M.</td><td>Shabat</td><td>${status('Esperando','amber')}</td><td><select class="filter"><option>Transferir</option><option>Conservar</option><option>Resolver antes</option></select></td></tr><tr><td>Comunidad Norte</td><td>Tefilá</td><td>${status('Seguimiento','blue')}</td><td><select class="filter"><option>Transferir</option><option>Conservar</option></select></td></tr><tr><td>José A.</td><td>Berajot</td><td>${status('Casi cerrado','green')}</td><td><select class="filter"><option>Resolver antes</option><option>Transferir</option></select></td></tr></tbody></table>`,'','flush')}${panel('Resumen para el siguiente jajam',`<div class="field"><label>Notas del turno</label><textarea style="min-height:110px">David espera definición sobre un caso de calentado. En Comunidad Norte falta revisar el contexto del mensaje anterior. José sólo requiere confirmación de cierre.</textarea></div><div class="check-line" style="margin-top:12px"><input type="checkbox" checked> Notificar al siguiente jajam</div><div class="check-line"><input type="checkbox" checked> Mantener auditoría de la entrega</div><button class="btn primary" style="width:100%;margin-top:14px" data-action="confirm-handoff">Entregar turno y finalizar</button>`)}</div>
  <div class="notice" style="margin-top:16px"><b>Si el siguiente jajam todavía no acepta</b><p>El turno actual continúa activo y los casos no quedan sin responsable. Dirección puede reasignar o activar al respaldo.</p></div>`}

function inbox(){return `${pageHead('Bandeja compartida','Cada pregunta tiene tema, responsable, SLA y decisión humana.',`<button class="btn">Disponibilidad</button><button class="btn primary" data-action="new-conversation">+ Nueva conversación</button>`)}<div class="chat-layout"><aside class="conversation-list"><div class="conversation-search"><input placeholder="Buscar conversación…"></div>${conversation('DM','David M.','¿Se puede calentar comida…','2 min','active')}${conversation('SR','Sara R.','Audio · 0:34','8 min','')}${conversation('Grupo','Comunidad Norte','@MaorHalaja una pregunta…','12 min','')}${conversation('JA','José A.','Gracias por la respuesta','28 min','')}${conversation('EM','Esther M.','Foto adjunta','41 min','')}</aside><section class="chat-main"><div class="chat-head"><div>${person('DM','David M.','WhatsApp privado')}</div><span class="tag amber">Esperando rabino</span></div><div class="messages" id="messages"><div class="bubble">Hola, ¿se puede calentar comida de cierta forma en Shabat?<small>10:58 · Recibido</small></div><div class="bubble out">Gracias. Un rabino está revisando tu pregunta.<small>10:58 · Sistema</small></div></div><div class="composer"><button class="icon-btn">＋</button><input id="chatInput" placeholder="Escribir respuesta para revisión…"><button class="btn primary" data-action="send-chat">Enviar</button></div></section><aside class="case-panel"><h3>Detalle del caso</h3><div class="sla">SLA: 13 min restantes</div><div class="case-field"><label>Tema</label><b>Shabat · Cocina</b></div><div class="case-field"><label>Responsable</label><b id="caseOwner">Sin asignar</b></div><div class="case-field"><label>Responder</label><b>En privado</b></div><div class="case-field"><label>Prioridad</label><b>Normal</b></div><button class="btn primary" style="width:100%" data-action="claim-case">Tomar caso</button><button class="btn" style="width:100%;margin-top:8px" data-action="suggest-answer">Sugerir desde biblioteca</button><p class="small" style="margin-top:14px">El sistema nunca responde una pregunta halájica sin revisión humana.</p></aside></div>`}
function conversation(i,n,msg,time,active){return `<div class="conversation ${active}"><span class="avatar">${i}</span><div><b>${n}</b><p>${msg}</p></div><time>${time}</time></div>`}

function halajaTeam(){return `${pageHead('Rabinos y disponibilidad','Temas, horarios, carga y reglas de asignación.',`<button class="btn primary" data-action="add-rabbi">+ Agregar rabino</button>`)}<div class="metric-grid">${metric('◎','7','Rabinos activos')}${metric('◷','3','Disponibles ahora')}${metric('◌','14','Casos en atención')}${metric('✓','92%','Dentro del SLA')}</div><div class="device-grid">${rabbi('RJ','R. Juni','Shabat · Kashrut','Disponible','green',4)}${rabbi('RN','R. Naftaly','Tefilá · Berajot','En estudio','amber',2)}${rabbi('RO','R. Ovadia','Familia · Festividades','Disponible','green',3)}</div>${panel('Reglas de asignación',`<table><thead><tr><th>Tema</th><th>Primario</th><th>Respaldo</th><th>Horario</th><th>SLA</th></tr></thead><tbody><tr><td>Shabat</td><td>R. Juni</td><td>R. Ovadia</td><td>08:00–22:00</td><td>30 min</td></tr><tr><td>Kashrut</td><td>R. Juni</td><td>R. Naftaly</td><td>09:00–20:00</td><td>30 min</td></tr><tr><td>Tefilá</td><td>R. Naftaly</td><td>Guardia</td><td>07:00–21:00</td><td>20 min</td></tr></tbody></table>`,'','flush')}`}
function rabbi(i,n,topics,avail,type,cases){return `<div class="device"><div class="device-head"><span class="avatar" style="width:43px;height:43px">${i}</span>${status(avail,type)}</div><h3>${n}</h3><p>${topics}</p><dl><div><dt>Casos abiertos</dt><dd>${cases}</dd></div><div><dt>Promedio</dt><dd>18 min</dd></div></dl><button class="btn small">Ver agenda</button></div>`}

function knowledge(){return `${pageHead('Respuestas aprobadas','Biblioteca para sugerir borradores; siempre requieren revisión humana.',`<button class="btn primary" data-action="new-article">+ Nueva respuesta</button>`)}<div class="filters"><input class="filter" placeholder="Buscar palabra o tema…"><select class="filter"><option>Todos los temas</option></select><select class="filter"><option>Aprobadas</option></select></div><div class="knowledge">${article('Shabat','Calentar comida seca','Aprobada por 2 rabinos','Hace 3 días')}${article('Berajot','Cambio de lugar','Aprobada por 1 rabino','Hace 1 semana')}${article('Kashrut','Utensilio de carne/leche','En revisión','Ayer')}${article('Tefilá','Olvido de Yaale Veyavó','Aprobada por 2 rabinos','Hace 2 semanas')}${article('Festividades','Preparación de Yom Tov','Aprobada por 2 rabinos','Hace 1 mes')}${article('Familia','Encendido de velas','Borrador','Hoy')}</div>`}
function article(tagName,title,stateText,updated){return `<div class="article"><span class="tag blue">${tagName}</span><h3>${title}</h3><p>Texto aprobado, fuentes y notas internas para orientar al rabino.</p><div class="task-foot"><span class="small">${updated}</span>${status(stateText,stateText.startsWith('Aprobada')?'green':stateText==='Borrador'?'':'amber')}</div></div>`}

function halajaAnalytics(){return `${pageHead('Métricas de atención','Volumen, tiempos, temas y carga sin evaluar el contenido halájico.',`<button class="btn">Exportar</button>`)}<div class="metric-grid">${metric('◌','386','Preguntas este mes','+18%')}${metric('◷','14 min','Primera atención','−3 min')}${metric('✓','27 min','Resolución promedio')}${metric('!','8%','Reabiertas','−1.2%')}</div><div class="grid-2">${panel('Volumen por día',`${bars([48,55,63,58,78,91,45],['Lun','Mar','Mié','Jue','Vie','Dom','Hoy'],true)}`)}${panel('Temas',`<div class="progress-list"><div class="progress-row"><b>Shabat</b><div class="track"><div class="fill" style="width:82%"></div></div><span>31%</span></div><div class="progress-row"><b>Kashrut</b><div class="track"><div class="fill" style="width:66%"></div></div><span>25%</span></div><div class="progress-row"><b>Tefilá</b><div class="track"><div class="fill" style="width:52%"></div></div><span>20%</span></div><div class="progress-row"><b>Familia</b><div class="track"><div class="fill" style="width:36%"></div></div><span>14%</span></div><div class="progress-row"><b>Otros</b><div class="track"><div class="fill" style="width:25%"></div></div><span>10%</span></div></div>`)} </div><div class="funnel"><div class="funnel-step">386<br>recibidas</div><div class="funnel-step">361<br>asignadas</div><div class="funnel-step">345<br>respondidas</div><div class="funnel-step">318<br>cerradas</div></div>`}

function halajaSettings(){return `${pageHead('Configuración de Maor Halajá','Reglas de entrada, grupos, SLA, retención y notificaciones.',`<button class="btn primary" data-action="save-settings">Guardar cambios</button>`)}<div class="settings-layout"><div class="settings-tabs"><button class="active">WhatsApp</button><button>Grupos</button><button>Temas</button><button>SLA y escalación</button><button>Retención</button><button>Plantillas</button><button>Seguridad</button></div><div>${panel('Comportamiento general',`<div class="form-grid"><div class="field"><label>Identidad de respuesta</label><select><option>Nombre del rabino + Maor Halajá</option></select></div><div class="field"><label>Tiempo antes de escalar</label><select><option>30 minutos</option></select></div><div class="field"><label>Mensajes de grupo que ingresan</label><select><option>Sólo menciones y respuestas</option></select></div><div class="field"><label>Casos sin reclamar</label><select><option>Asignar a guardia</option></select></div><div class="field"><label>Retención de conversaciones</label><select><option>24 meses</option></select></div><div class="field"><label>Audio</label><select><option>Transcribir para búsqueda</option></select></div></div>`)}${panel('Protecciones',`<div class="activity"><div class="activity-item"><span class="activity-icon">人</span><div><b>Aprobación humana obligatoria</b><p>Ninguna respuesta halájica se envía sola.</p></div><input type="checkbox" checked disabled></div><div class="activity-item"><span class="activity-icon">✓</span><div><b>Evitar respuestas simultáneas</b><p>Bloquear caso cuando un rabino lo toma.</p></div><input type="checkbox" checked></div><div class="activity-item"><span class="activity-icon">◷</span><div><b>Alertas por SLA</b><p>Notificar y escalar casos desatendidos.</p></div><input type="checkbox" checked></div></div>`)}</div></div>`}

const pages={overview,clients,sales,seller,'client-portal':clientPortal,collections,routes,cash,bank,raffles,screens,thanks,expenses,attendance,payroll,reports,admin,audit,'rabbi-panel':rabbiPanel,'shift-handoff':shiftHandoff,inbox,'halaja-team':halajaTeam,knowledge,'halaja-analytics':halajaAnalytics,'halaja-settings':halajaSettings};

function renderNav(){let group='';$('#mainNav').innerHTML=nav[state.workspace].map(item=>{let out='';if(item.group&&item.group!==group){group=item.group;out+=`<div class="nav-label">${group}</div>`}return out+`<button class="nav-item ${state.view===item.id?'active':''}" data-view="${item.id}"><span class="nav-icon">${item.icon}</span>${item.label}</button>`}).join('')}
function render(){if(!pages[state.view]) state.view=state.workspace==='kma'?'overview':'rabbi-panel';renderNav();$('#pageTitle').textContent=titles[state.view];$('#breadcrumbs').textContent=`${state.workspace==='kma'?'KMA':'Maor Halajá'} / ${titles[state.view]}`;$('#content').innerHTML=pages[state.view]();bindLiveInputs();window.scrollTo({top:0,behavior:'smooth'})}
function bindLiveInputs(){const t=$('#screenTitleInput'),s=$('#screenSubtitleInput');if(t)t.addEventListener('input',e=>{state.screenTitle=e.target.value;$('#canvasTitle').textContent=e.target.value});if(s)s.addEventListener('input',e=>{state.screenSubtitle=e.target.value;$('#canvasSubtitle').textContent=e.target.value})}
function toast(message,type=''){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;$('#toasts').append(el);setTimeout(()=>el.remove(),3200)}
function showModal(html){$('#modal').innerHTML=html;$('#modalBackdrop').hidden=false}
function closeModal(){if($('#dontShow')?.checked)localStorage.setItem('maor-demo-seen','1');$('#modalBackdrop').hidden=true}
function showDisclaimer(){showModal($('#disclaimerTemplate').innerHTML)}
function formModal(title,body,button='Guardar demo'){showModal(`<div class="modal-hero"><span class="demo-chip">SIMULACIÓN</span><h2>${title}</h2><p>Los datos capturados aquí son ficticios y no se guardan.</p></div><div style="padding:14px 2px">${body}</div><div class="modal-actions"><button class="btn" data-action="close-modal">Cancelar</button><button class="btn primary" data-action="save-demo">${button}</button></div>`)}

document.addEventListener('click',e=>{
  const view=e.target.closest('[data-view]');if(view){state.view=view.dataset.view;render();$('#sidebar').classList.remove('open');return}
  const ws=e.target.closest('[data-workspace]');if(ws){state.workspace=ws.dataset.workspace;state.view=state.workspace==='kma'?'overview':'rabbi-panel';$$('.workspace').forEach(x=>x.classList.toggle('active',x===ws));render();return}
  const a=e.target.closest('[data-action]');if(!a)return;const action=a.dataset.action;
  if(action==='show-disclaimer')showDisclaimer();
  else if(action==='close-modal')closeModal();
  else if(action==='save-demo'){closeModal();toast('Simulación guardada correctamente.','success')}
  else if(action==='new-sale')formModal('Registrar nueva venta',`<div class="form-grid"><div class="field"><label>Cliente</label><input value="Abraham M."></div><div class="field"><label>Concepto</label><select><option>Día de estudio</option><option>Rifa 2027</option><option>Mensualidad</option></select></div><div class="field"><label>Importe</label><input value="$12,000"></div><div class="field"><label>Vendedor</label><select><option>R. David</option></select></div><div class="field" style="grid-column:1/-1"><label>Dedicatoria</label><textarea>En mérito de la familia…</textarea></div></div>`,'Crear venta y flujos');
  else if(action==='new-client')formModal('Nuevo cliente',`<div class="form-grid"><div class="field"><label>Nombre</label><input></div><div class="field"><label>Tipo</label><select><option>Donante</option><option>Cliente</option></select></div><div class="field"><label>Teléfono</label><input></div><div class="field"><label>Secretaría responsable</label><select><option>Secretaría 1</option></select></div></div>`);
  else if(action==='quick-announcement')formModal('Crear anuncio rápido',`<div class="form-grid"><div class="field"><label>Diseño</label><select><option>Aviso de tefilá</option><option>Diseño libre</option></select></div><div class="field"><label>Pantallas</label><select><option>Todas</option><option>Entrada</option></select></div><div class="field" style="grid-column:1/-1"><label>Mensaje</label><input value="Minjá hoy 1:45 pm"></div><div class="field"><label>Transición</label><select><option>Desvanecer</option><option>Deslizar</option></select></div><div class="field"><label>Tiempo visible</label><select><option>20 segundos</option><option>1 minuto</option></select></div></div>`,'Publicar anuncio');
  else if(action==='publish-screen'){toast('Contenido publicado en 2 pantallas.','success')}
  else if(action==='preview-screen'){toast('Vista previa abierta en modo pantalla.')}
  else if(action==='reconcile'){a.closest('.bank-row').querySelector('button').outerHTML='<span class="tag green">Aplicado</span>';toast('Movimiento conciliado.','success')}
  else if(action==='sync-readers'){toast('Sincronizando los 3 lectores…','success');setTimeout(()=>toast('Lectores al día. 0 eventos pendientes.','success'),900)}
  else if(action==='calculate-payroll'){toast('Cálculo preliminar generado con 4 incidencias por revisar.','success')}
  else if(action==='claim-case'){state.claimed=true;$('#caseOwner').textContent='R. Juni';a.textContent='Caso tomado';a.disabled=true;toast('Caso asignado.','success')}
  else if(action==='suggest-answer'){if($('#chatInput'))$('#chatInput').value='Borrador sugerido desde respuesta aprobada. Revisar fuentes y adaptar antes de enviar.';toast('Borrador insertado; requiere revisión humana.','warn')}
  else if(action==='send-chat'){const input=$('#chatInput');if(input&&input.value.trim()){const b=document.createElement('div');b.className='bubble out';b.innerHTML=`${input.value}<small>Ahora · Pendiente de envío simulado</small>`;$('#messages').append(b);input.value='';toast('Respuesta simulada registrada.','success')}}
  else if(action==='rabbi-filter'){$$('[data-action="rabbi-filter"]').forEach(x=>x.classList.toggle('primary',x===a));toast(action&&a.dataset.filter==='all'?'Mostrando todos los casos del equipo.':'Mostrando únicamente tus casos.')}
  else if(action==='open-rabbi-case'){state.view='inbox';render();toast('Caso abierto en la bandeja compartida.')}
  else if(action==='end-shift'||action==='switch-shift'){state.view='shift-handoff';render();toast(action==='end-shift'?'Prepara la entrega antes de finalizar.':'Cambio anticipado iniciado.','warn')}
  else if(action==='confirm-handoff'){formModal('Confirmar entrega de turno',`<div class="notice"><b>R. Naftaly recibirá 2 casos abiertos</b><p>Tu turno permanecerá activo hasta que el siguiente jajam acepte la entrega.</p></div><div class="field" style="margin-top:14px"><label>Confirmación</label><input value="Escribe ENTREGAR para confirmar"></div>`,'Confirmar entrega')}
  else if(action==='ticket'){a.classList.toggle('partial');toast('Boleto seleccionado para una venta simulada.')}
  else if(['save-settings','export','auto-match','payment','impersonate','new-task','new-route','cash-transfer','sell-ticket','new-thanks','new-expense','new-report','open-record','device-detail','add-rabbi','new-article','new-conversation','notify','profile'].includes(action))toast('Acción simulada en este demo.','success');
});

$('#openNav').addEventListener('click',()=>$('#sidebar').classList.add('open'));
$('#closeNav').addEventListener('click',()=>$('#sidebar').classList.remove('open'));
$('#modalBackdrop').addEventListener('click',e=>{if(e.target===$('#modalBackdrop'))closeModal()});
$('#globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){toast(`Búsqueda simulada: “${e.target.value}”`);e.target.blur()}});

$$('.workspace').forEach(x=>x.classList.toggle('active',x.dataset.workspace===state.workspace));
render();
if(!demoParams.has('skipIntro')&&!localStorage.getItem('maor-demo-seen'))setTimeout(showDisclaimer,250);
